#!/usr/bin/env bash
# Spec: docs/specs/platform.md
# Merge config/env.shared.example + .env.shared.local + config/env.{env}.example
# → .env.development | .env.production (+ apps/portal/.env for development)
#
# Usage:
#   ./scripts/env-build.sh development
#   ./scripts/env-build.sh production
#   ./scripts/env-build.sh production --check   # validate only, no write

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_NAME="${1:-}"
CHECK_ONLY=false

if [[ "${2:-}" == "--check" ]]; then
  CHECK_ONLY=true
fi

if [[ "$ENV_NAME" != "development" && "$ENV_NAME" != "production" ]]; then
  echo "Usage: $0 <development|production> [--check]" >&2
  exit 1
fi

SHARED_EXAMPLE="$ROOT/config/env.shared.example"
ENV_EXAMPLE="$ROOT/config/env.$ENV_NAME.example"
SHARED_LOCAL="${ENV_SHARED_LOCAL:-$ROOT/.env.shared.local}"
ENV_EXTRA="${ENV_EXTRA:-}"
OUTPUT="$ROOT/.env.$ENV_NAME"

for f in "$SHARED_EXAMPLE" "$ENV_EXAMPLE"; do
  if [[ ! -f "$f" ]]; then
    echo "Missing required file: $f" >&2
    exit 1
  fi
done

if [[ ! -f "$SHARED_LOCAL" ]]; then
  echo "Missing secrets file: $SHARED_LOCAL" >&2
  echo "Run: cp config/env.shared.example .env.shared.local" >&2
  exit 1
fi

MERGE_FILES=("$SHARED_EXAMPLE" "$SHARED_LOCAL" "$ENV_EXAMPLE")
if [[ -n "$ENV_EXTRA" && -f "$ENV_EXTRA" ]]; then
  MERGE_FILES+=("$ENV_EXTRA")
fi

# Parse KEY=VALUE lines (ignore comments and blanks). Last file wins for duplicate keys.
merge_env_files() {
  local tmp
  tmp="$(mktemp)"
  : > "$tmp"
  for file in "$@"; do
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
      if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        val="${BASH_REMATCH[2]}"
        grep -v "^${key}=" "$tmp" > "${tmp}.new" 2>/dev/null || true
        mv "${tmp}.new" "$tmp"
        printf '%s=%s\n' "$key" "$val" >> "$tmp"
      fi
    done < "$file"
  done
  cat "$tmp"
  rm -f "$tmp"
}

MERGED="$(merge_env_files "${MERGE_FILES[@]}")"

# Sync DATABASE_URL password with MYSQL_PASSWORD
MYSQL_PASSWORD="$(printf '%s\n' "$MERGED" | awk -F= '/^MYSQL_PASSWORD=/{print substr($0,index($0,"=")+1); exit}')"
if [[ -n "$MYSQL_PASSWORD" ]]; then
  MERGED="$(printf '%s\n' "$MERGED" | awk -v pw="$MYSQL_PASSWORD" '
    /^DATABASE_URL=/ {
      sub(/mysql:\/\/wechat:[^@]*@/, "mysql://wechat:" pw "@")
    }
    { print }
  ')"
fi

write_portal_env() {
  local src="$1"
  local portal_keys=(ADMIN_PASSWORD DB_PATH UPLOADS_DIR PORT NODE_ENV CLIENT_ORIGIN)
  local out="$ROOT/apps/portal/.env"
  {
    echo "# Generated by scripts/env-build.sh — do not edit manually"
    for key in "${portal_keys[@]}"; do
      line="$(printf '%s\n' "$src" | grep "^${key}=" || true)"
      if [[ -n "$line" ]]; then
        echo "$line"
      fi
    done
  } > "$out"
}

validate_merged() {
  local errors=0
  if printf '%s\n' "$MERGED" | grep -q 'CHANGE_ME'; then
    echo "❌ Found CHANGE_ME placeholders in merged env:" >&2
    printf '%s\n' "$MERGED" | grep 'CHANGE_ME' >&2
    errors=$((errors + 1))
  fi
  local db_pw url_pw
  db_pw="$(printf '%s\n' "$MERGED" | awk -F= '/^MYSQL_PASSWORD=/{print substr($0,index($0,"=")+1); exit}')"
  url_pw="$(printf '%s\n' "$MERGED" | sed -n 's|^DATABASE_URL=mysql://wechat:\([^@]*\)@.*|\1|p' | head -1)"
  if [[ -n "$db_pw" && -n "$url_pw" && "$db_pw" != "$url_pw" ]]; then
    echo "❌ DATABASE_URL password does not match MYSQL_PASSWORD" >&2
    errors=$((errors + 1))
  fi
  return "$errors"
}

if $CHECK_ONLY; then
  if [[ -f "$OUTPUT" && -z "${ENV_SHARED_LOCAL:-}" && -z "${ENV_EXTRA:-}" ]]; then
    MERGED="$(grep -v '^#' "$OUTPUT" | grep '=' || true)"
  else
    MERGE_FILES=("$SHARED_EXAMPLE" "$SHARED_LOCAL" "$ENV_EXAMPLE")
    if [[ -n "$ENV_EXTRA" && -f "$ENV_EXTRA" ]]; then
      MERGE_FILES+=("$ENV_EXTRA")
    fi
    MERGED="$(merge_env_files "${MERGE_FILES[@]}")"
    MYSQL_PASSWORD="$(printf '%s\n' "$MERGED" | awk -F= '/^MYSQL_PASSWORD=/{print substr($0,index($0,"=")+1); exit}')"
    if [[ -n "$MYSQL_PASSWORD" ]]; then
      MERGED="$(printf '%s\n' "$MERGED" | awk -v pw="$MYSQL_PASSWORD" '
        /^DATABASE_URL=/ { sub(/mysql:\/\/wechat:[^@]*@/, "mysql://wechat:" pw "@") }
        { print }
      ')"
    fi
  fi
  if validate_merged; then
    echo "✅ $ENV_NAME env valid"
  else
    exit 1
  fi
  exit 0
fi

{
  echo "# Generated by scripts/env-build.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# Source: config/env.shared.example + .env.shared.local + config/env.$ENV_NAME.example"
  echo "# Do not edit manually — re-run: ./scripts/env-build.sh $ENV_NAME"
  echo ""
  printf '%s\n' "$MERGED"
} > "$OUTPUT"

if [[ "$ENV_NAME" == "development" ]]; then
  write_portal_env "$MERGED"
  echo "✅ Wrote $OUTPUT"
  echo "✅ Wrote apps/portal/.env"
else
  echo "✅ Wrote $OUTPUT"
fi

if ! validate_merged; then
  echo "⚠️  Wrote file but validation failed — fill .env.shared.local and re-run" >&2
  exit 1
fi

echo "✅ $ENV_NAME environment ready"
