// ⚠️ 生成物，勿手改 —— 由 scripts/lab/gen-asset-manifest.mjs 从
//    lib/lab/domain/rooms/*.ts 与 components/lab/** 派生。
//    改资源请改那些来源，然后运行：
//        node scripts/lab/gen-asset-manifest.mjs
//
//    存在的理由见 ADR 20260903140615：预载表原先手写，与渲染树漂移后
//    表现为"为死代码预载纹理"与"漏收云纹理导致灰矩形"，两者都不报错。

import { DERIVED_CORRIDOR_TEXTURES } from '@/lib/lab/domain/corridor/assets'
import { getCorridorMuralTexturePaths } from '@/lib/lab/corridorMurals'

/**
 * 走廊几何、门、装饰用到的纹理 —— 进首屏 loader。
 *
 * 三部分：静态扫描到的字面量、domain 里按规则算出的组（头像 9 帧 +
 * 门贴图 sketch/painted 两层）、以及从相册取的壁画。后两类是模板字面量
 * 或数据驱动，静态扫描抓不到——漏它们的表现不是报错，是走廊走到一半
 * 突然闪空。
 */
const CORRIDOR_TEXTURE_LITERALS: readonly string[] = [
  '/textures/corridor/bokilampy.webp',
  '/textures/corridor/bug_sketch.webp',
  '/textures/corridor/ceiling_texture.webp',
  '/textures/corridor/decorations/coffee_debug.webp',
  '/textures/corridor/decorations/idea_process.webp',
  '/textures/corridor/decorations/while_true_loop.webp',
  '/textures/corridor/doodles/coffee_cup.webp',
  '/textures/corridor/doodles/paper_airplane.webp',
  '/textures/corridor/doodles/paper_ball.webp',
  '/textures/corridor/doodles/pencil.webp',
  '/textures/corridor/doors/backsingledoors.webp',
  '/textures/corridor/doors/doorrleft.webp',
  '/textures/corridor/doors/dorright.webp',
  '/textures/corridor/doors/klamkadodrzwi.webp',
  '/textures/corridor/doors/klamkadodrzwi_painted.webp',
  '/textures/corridor/doors/ramkasingledoors.webp',
  '/textures/corridor/drzewkowdoniczce.webp',
  '/textures/corridor/gorastolika.webp',
  '/textures/corridor/ink_splash.webp',
  '/textures/corridor/kawalekpodlogi.webp',
  '/textures/corridor/kratanalampy.webp',
  '/textures/corridor/kratkawentylacyjna.webp',
  '/textures/corridor/kwiatekwdoniczce.webp',
  '/textures/corridor/pustatabliczka.webp',
  '/textures/corridor/ramkanazdjeciemala.webp',
  '/textures/corridor/strzalka.webp',
  '/textures/corridor/szafkaprzod.webp',
  '/textures/corridor/szafkaprzodgora.webp',
  '/textures/corridor/texturadoprogow.webp',
  '/textures/corridor/texturadrewnadonozekbiurka.webp',
  '/textures/corridor/wall_texture.webp',
] as const

/** 首屏只载前 1 段的壁画；更深的段在 idle 时预取（审计 G1：原先要下完 7.6MB 才退场） */
export const FIRST_SCREEN_MURAL_SEGMENTS = 1

export const CORRIDOR_TEXTURES: readonly string[] = [
  ...new Set([
    ...CORRIDOR_TEXTURE_LITERALS,
    ...DERIVED_CORRIDOR_TEXTURES,
    ...getCorridorMuralTexturePaths(FIRST_SCREEN_MURAL_SEGMENTS),
  ]),
]

/** 每个房间声明的资源 —— 按门位距离在 idle 时预取 */
export const ROOM_ASSETS: Readonly<Record<string, readonly string[]>> = {
  about: [
    '/textures/about/awatarnachmurce.webp',
    '/textures/about/freelancewyspa.webp',
    '/textures/about/uowyspa.webp',
    '/textures/clouds/1131c3eb-dfae-423f-924b-ff39d8ccd6dc.webp',
    '/textures/clouds/254b8ec8-d6f7-4275-956f-7bab65b2ce2d.webp',
    '/textures/clouds/2cc88dd1-483c-466d-b07e-f8308c61ccbe.webp',
    '/textures/clouds/5606fcc0-3252-447d-a58a-7bcbac73229a.webp',
    '/textures/clouds/7882dc72-3d01-41fb-ac0e-d07b0184ebc1.webp',
    '/textures/clouds/9b2ca72f-7bd0-473b-ba6e-dd9e0eb79d35.webp',
    '/textures/clouds/c83293c6-d90c-4a32-8d9d-5ac9af7e2296.webp',
    '/textures/clouds/f6e358bc-d27c-41dd-95f4-6787a835c41e.webp',
  ],
  projects: [
    '/textures/corridor/bokilampy.webp',
    '/textures/corridor/ceiling_texture.webp',
    '/textures/corridor/kawalekpodlogi.webp',
    '/textures/corridor/kratanalampy.webp',
    '/textures/corridor/texturadoprogow.webp',
    '/textures/corridor/wall_texture.webp',
    '/textures/studio/monitor_back.webp',
    '/textures/studio/monitor_back_painted.webp',
    '/textures/studio/monitor_bottom.webp',
    '/textures/studio/monitor_bottom_painted.webp',
    '/textures/studio/monitor_front.webp',
    '/textures/studio/monitor_front_painted.webp',
    '/textures/studio/monitor_left.webp',
    '/textures/studio/monitor_left_painted.webp',
    '/textures/studio/monitor_right.webp',
    '/textures/studio/monitor_right_painted.webp',
    '/textures/studio/monitor_top.webp',
    '/textures/studio/monitor_top_painted.webp',
  ],
  publications: [
    '/textures/clouds/1131c3eb-dfae-423f-924b-ff39d8ccd6dc.webp',
    '/textures/clouds/254b8ec8-d6f7-4275-956f-7bab65b2ce2d.webp',
    '/textures/clouds/2cc88dd1-483c-466d-b07e-f8308c61ccbe.webp',
    '/textures/clouds/5606fcc0-3252-447d-a58a-7bcbac73229a.webp',
    '/textures/clouds/7882dc72-3d01-41fb-ac0e-d07b0184ebc1.webp',
    '/textures/clouds/9b2ca72f-7bd0-473b-ba6e-dd9e0eb79d35.webp',
    '/textures/clouds/c83293c6-d90c-4a32-8d9d-5ac9af7e2296.webp',
    '/textures/clouds/f6e358bc-d27c-41dd-95f4-6787a835c41e.webp',
    '/textures/corridor/texturadoprogow.webp',
    '/textures/gallery/bioprzod.webp',
    '/textures/gallery/bioprzod_painted.webp',
    '/textures/gallery/bird_gray.webp',
    '/textures/gallery/domki.webp',
    '/textures/gallery/floor.webp',
    '/textures/gallery/klamerka.webp',
    '/textures/gallery/miastotlo.webp',
    '/textures/gallery/monetuneprzod.webp',
    '/textures/gallery/monetuneprzod_painted.webp',
    '/textures/gallery/przyciskdotylukartki.webp',
    '/textures/gallery/przyciskdotylukartki_painted.webp',
    '/textures/gallery/railing.webp',
    '/textures/gallery/timberkittyprzod.webp',
    '/textures/gallery/timberkittyprzod_painted.webp',
    '/textures/gallery/tylkartki.webp',
    '/textures/gallery/tylkartki_painted.webp',
    '/textures/gallery/youngmultiprzod.webp',
    '/textures/gallery/youngmultiprzod_painted.webp',
  ],
  contact: [
    '/textures/clouds/1131c3eb-dfae-423f-924b-ff39d8ccd6dc.webp',
    '/textures/clouds/254b8ec8-d6f7-4275-956f-7bab65b2ce2d.webp',
    '/textures/clouds/2cc88dd1-483c-466d-b07e-f8308c61ccbe.webp',
    '/textures/clouds/5606fcc0-3252-447d-a58a-7bcbac73229a.webp',
    '/textures/clouds/7882dc72-3d01-41fb-ac0e-d07b0184ebc1.webp',
    '/textures/clouds/9b2ca72f-7bd0-473b-ba6e-dd9e0eb79d35.webp',
    '/textures/clouds/c83293c6-d90c-4a32-8d9d-5ac9af7e2296.webp',
    '/textures/clouds/f6e358bc-d27c-41dd-95f4-6787a835c41e.webp',
    '/textures/contact/beczka.webp',
    '/textures/contact/beczka_painted.webp',
    '/textures/contact/faletopdown.webp',
    '/textures/contact/latarnia.webp',
    '/textures/contact/molo.webp',
    '/textures/contact/paper_form.webp',
    '/textures/contact/send_button.webp',
    '/textures/contact/statek.webp',
  ],
  gallery: [
  ],
} as const

/** 音频清单里出现的全部文件 */
export const SOUND_FILES: readonly string[] = [
  '/sounds/achievement_chime.m4a',
  '/sounds/amb_about.m4a',
  '/sounds/amb_contact.m4a',
  '/sounds/amb_projects.m4a',
  '/sounds/amb_publications.m4a',
  '/sounds/bg_corridor.m4a',
  '/sounds/bg_corridor.ogg',
  '/sounds/door_close.mp3',
  '/sounds/door_hover.mp3',
  '/sounds/door_open.mp3',
  '/sounds/papersound.mp3',
] as const

/** 全部资源的扁平去重列表（供存在性校验用） */
export const ALL_ASSETS: readonly string[] = [
  '/sounds/achievement_chime.m4a',
  '/sounds/amb_about.m4a',
  '/sounds/amb_contact.m4a',
  '/sounds/amb_projects.m4a',
  '/sounds/amb_publications.m4a',
  '/sounds/bg_corridor.m4a',
  '/sounds/bg_corridor.ogg',
  '/sounds/door_close.mp3',
  '/sounds/door_hover.mp3',
  '/sounds/door_open.mp3',
  '/sounds/papersound.mp3',
  '/textures/about/awatarnachmurce.webp',
  '/textures/about/freelancewyspa.webp',
  '/textures/about/uowyspa.webp',
  '/textures/clouds/1131c3eb-dfae-423f-924b-ff39d8ccd6dc.webp',
  '/textures/clouds/254b8ec8-d6f7-4275-956f-7bab65b2ce2d.webp',
  '/textures/clouds/2cc88dd1-483c-466d-b07e-f8308c61ccbe.webp',
  '/textures/clouds/5606fcc0-3252-447d-a58a-7bcbac73229a.webp',
  '/textures/clouds/7882dc72-3d01-41fb-ac0e-d07b0184ebc1.webp',
  '/textures/clouds/9b2ca72f-7bd0-473b-ba6e-dd9e0eb79d35.webp',
  '/textures/clouds/c83293c6-d90c-4a32-8d9d-5ac9af7e2296.webp',
  '/textures/clouds/f6e358bc-d27c-41dd-95f4-6787a835c41e.webp',
  '/textures/contact/beczka.webp',
  '/textures/contact/beczka_painted.webp',
  '/textures/contact/faletopdown.webp',
  '/textures/contact/latarnia.webp',
  '/textures/contact/molo.webp',
  '/textures/contact/paper_form.webp',
  '/textures/contact/send_button.webp',
  '/textures/contact/statek.webp',
  '/textures/corridor/bokilampy.webp',
  '/textures/corridor/bug_sketch.webp',
  '/textures/corridor/ceiling_texture.webp',
  '/textures/corridor/decorations/coffee_debug.webp',
  '/textures/corridor/decorations/idea_process.webp',
  '/textures/corridor/decorations/while_true_loop.webp',
  '/textures/corridor/doodles/coffee_cup.webp',
  '/textures/corridor/doodles/paper_airplane.webp',
  '/textures/corridor/doodles/paper_ball.webp',
  '/textures/corridor/doodles/pencil.webp',
  '/textures/corridor/doors/backsingledoors.webp',
  '/textures/corridor/doors/doorrleft.webp',
  '/textures/corridor/doors/dorright.webp',
  '/textures/corridor/doors/klamkadodrzwi.webp',
  '/textures/corridor/doors/klamkadodrzwi_painted.webp',
  '/textures/corridor/doors/ramkasingledoors.webp',
  '/textures/corridor/drzewkowdoniczce.webp',
  '/textures/corridor/gorastolika.webp',
  '/textures/corridor/ink_splash.webp',
  '/textures/corridor/kawalekpodlogi.webp',
  '/textures/corridor/kratanalampy.webp',
  '/textures/corridor/kratkawentylacyjna.webp',
  '/textures/corridor/kwiatekwdoniczce.webp',
  '/textures/corridor/pustatabliczka.webp',
  '/textures/corridor/ramkanazdjeciemala.webp',
  '/textures/corridor/strzalka.webp',
  '/textures/corridor/szafkaprzod.webp',
  '/textures/corridor/szafkaprzodgora.webp',
  '/textures/corridor/texturadoprogow.webp',
  '/textures/corridor/texturadrewnadonozekbiurka.webp',
  '/textures/corridor/wall_texture.webp',
  '/textures/gallery/bioprzod.webp',
  '/textures/gallery/bioprzod_painted.webp',
  '/textures/gallery/bird_gray.webp',
  '/textures/gallery/domki.webp',
  '/textures/gallery/floor.webp',
  '/textures/gallery/klamerka.webp',
  '/textures/gallery/miastotlo.webp',
  '/textures/gallery/monetuneprzod.webp',
  '/textures/gallery/monetuneprzod_painted.webp',
  '/textures/gallery/przyciskdotylukartki.webp',
  '/textures/gallery/przyciskdotylukartki_painted.webp',
  '/textures/gallery/railing.webp',
  '/textures/gallery/timberkittyprzod.webp',
  '/textures/gallery/timberkittyprzod_painted.webp',
  '/textures/gallery/tylkartki.webp',
  '/textures/gallery/tylkartki_painted.webp',
  '/textures/gallery/youngmultiprzod.webp',
  '/textures/gallery/youngmultiprzod_painted.webp',
  '/textures/studio/monitor_back.webp',
  '/textures/studio/monitor_back_painted.webp',
  '/textures/studio/monitor_bottom.webp',
  '/textures/studio/monitor_bottom_painted.webp',
  '/textures/studio/monitor_front.webp',
  '/textures/studio/monitor_front_painted.webp',
  '/textures/studio/monitor_left.webp',
  '/textures/studio/monitor_left_painted.webp',
  '/textures/studio/monitor_right.webp',
  '/textures/studio/monitor_right_painted.webp',
  '/textures/studio/monitor_top.webp',
  '/textures/studio/monitor_top_painted.webp',
] as const
