export const PUBLICATION_CAROUSEL_ITEM_GAP = 2.5
export const PUBLICATION_CAROUSEL_WHEEL_SENSITIVITY = 0.005
export const PUBLICATION_CAROUSEL_LERP_SPEED = 5
export const PUBLICATION_CAROUSEL_MAX_DELTA_ULPS = 4
